// Material 3 color roles generated once from the brand seed #1e3a8a with
// @material/material-color-utilities (SchemeContent): primary-container is
// exactly the brand blue. Hardcoded so the generator is not shipped.
export const M3_PALETTE = {
  "light": {
    "primary": "#00236f",
    "on-primary": "#ffffff",
    "primary-container": "#1e3a8a",
    "on-primary-container": "#90a8ff",
    "secondary": "#555d7e",
    "on-secondary": "#ffffff",
    "secondary-container": "#d0d8ff",
    "on-secondary-container": "#555e7f",
    "tertiary": "#490b56",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#62266e",
    "on-tertiary-container": "#d993e2",
    "error": "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#93000a",
    "background": "#faf8ff",
    "on-background": "#1a1b21",
    "surface": "#faf8ff",
    "on-surface": "#1a1b21",
    "surface-variant": "#e1e1ef",
    "on-surface-variant": "#444651",
    "surface-dim": "#dad9e1",
    "surface-bright": "#faf8ff",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f4f3fa",
    "surface-container": "#eeedf4",
    "surface-container-high": "#e9e7ef",
    "surface-container-highest": "#e3e1e9",
    "outline": "#757682",
    "outline-variant": "#c5c5d3",
    "inverse-surface": "#2f3036",
    "inverse-on-surface": "#f1f0f7",
    "inverse-primary": "#b6c4ff"
  },
  "dark": {
    "primary": "#b6c4ff",
    "on-primary": "#05297a",
    "primary-container": "#1e3a8a",
    "on-primary-container": "#90a8ff",
    "secondary": "#bdc5eb",
    "on-secondary": "#262f4d",
    "secondary-container": "#3d4565",
    "on-secondary-container": "#abb4d9",
    "tertiary": "#f6adff",
    "on-tertiary": "#50145d",
    "tertiary-container": "#62266e",
    "on-tertiary-container": "#d993e2",
    "error": "#ffb4ab",
    "on-error": "#690005",
    "error-container": "#93000a",
    "on-error-container": "#ffdad6",
    "background": "#121318",
    "on-background": "#e3e1e9",
    "surface": "#121318",
    "on-surface": "#e3e1e9",
    "surface-variant": "#444651",
    "on-surface-variant": "#c5c5d3",
    "surface-dim": "#121318",
    "surface-bright": "#38393f",
    "surface-container-lowest": "#0d0e13",
    "surface-container-low": "#1a1b21",
    "surface-container": "#1e1f25",
    "surface-container-high": "#292a2f",
    "surface-container-highest": "#34343a",
    "outline": "#8f909d",
    "outline-variant": "#444651",
    "inverse-surface": "#e3e1e9",
    "inverse-on-surface": "#2f3036",
    "inverse-primary": "#4059aa"
  }
};
